version: '3.5'
services:
  pos-order-service:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    entrypoint: /etc/entrypoint.sh
    volumes:
      - ../../:/var/www
      - ../../composer-auth.json:/root/.composer/auth.json
      - ../nginx/conf.d/nginx-dev.conf:/etc/nginx/sites-enabled/default
      - ../supervisor/conf.d/horizon.conf:/etc/supervisor/conf.d/horizon.conf
      - ../php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ../php/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
      - ../php/php.ini:/usr/local/etc/php/conf.d/php.override.ini
      - ../php/conf.d/www.local.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - ${EXPORTED_PORT}:80
    networks:
      - pos-order-service-network

networks:
  pos-order-service-network:
    external:
      name: ${EXTERNAL_NETWORK}
